sudo: false


language: go
go:
  - 1.8
  
install:
  - go get github.com/whyrusleeping/gx
  - go get github.com/whyrusleeping/gx-go
  - gx install --global

script:
  - go vet
  - gx test -v -race ./...

cache:
  directories:
    - $GOPATH/src/gx

notifications:
email: false
  
